name: Feature
on: [pull_request]
jobs:
  Feature:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild -scheme Simplog
      - run: xcodebuild -scheme SimplogDisabled
      - run: swift test